CREATE DATABASE Prueba_app

USE Prueba_app

CREATE TABLE Departamento
(
	Id INT NOT NULL IDENTITY(1,1),
	Codigo VARCHAR(150) NOT NULL,
	Nombre VARCHAR(350) NOT NULL,
	Activo BIT DEFAULT 1,
	CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (Id)
)

CREATE TABLE Cargo
(
	Id INT NOT NULL IDENTITY(1,1),
	Codigo VARCHAR(150) NOT NULL,
	Nombre VARCHAR(350) NOT NULL,
	Activo BIT DEFAULT 1,
	CONSTRAINT PK_CARGO PRIMARY KEY (Id)
)

CREATE TABLE Usuario(
	Id INT NOT NULL IDENTITY(1,1),
	PrimerNombre VARCHAR(150) NOT NULL,
	SegundoNombre VARCHAR(150),
	PrimerApellido VARCHAR(150) NOT NULL,
	SegundoApellido VARCHAR(150),
	IdDepartamento INT NOT NULL,
	IdCargo INT NOT NULL,
	CONSTRAINT PK_USUARIO PRIMARY KEY(Id),
	CONSTRAINT FK_USUARIO_DEPARTAMENTO FOREIGN KEY (IdDepartamento) REFERENCES Departamento(Id),
	CONSTRAINT FK_USUARIO_CARGO FOREIGN KEY (IdCargo) REFERENCES Cargo(Id),
)

INSERT INTO Departamento(Codigo, Nombre) VALUES ('SIS-TICS', 'SISTEMAS')
INSERT INTO Departamento(Codigo, Nombre) VALUES ('CONT', 'Contabilidad')

INSERT INTO Cargo(Codigo, Nombre) VALUES ('DEV-FRONT', 'Programador FrontEnd')
INSERT INTO Cargo(Codigo, Nombre) VALUES ('ANALISTA', 'Contable')

SELECT * FROM Departamento
SELECT * FROM Cargo
